working_directory = "C:/Users/myshkovsky"
live_config_reload = true

[shell]
program = "pwsh"
args = ["-nologo"]

[font]
normal = { family = "Noto Sans Mono", style = "Regular" }
italic = { style = "ExtraLight" }
bold_italic = { style = "SemiBold" }
size = 12.0
offset = { x = 1, y = 0 }

[window]
position = { x = 500, y = 30 }
dimensions = { columns = 90, lines = 46 }
padding = { x = 0, y = 0 }
resize_increments = true

[mouse]
hide_when_typing = true

[colors]
draw_bold_text_with_bright_colors = true

[colors.normal]
red = "#cc5555"
green = "#55cc55"
blue = "#5555cc"
cyan = "#7acaca"
magenta = "#cc55cc"
yellow = "#cdcd55"
white = "#cccccc"

[colors.bright]
red = "#ff5555"
green = "#55ff55"
blue = "#5555ff"
cyan = "#55ffff"
magenta = "#ff55ff"
yellow = "#ffff55"
white = "#000000"

[colors.primary]
background = "#000000"
